version: "3"
services:

  linux:
    build: ./linux
    domainname: netlab
    dns_search: netlab
    hostname: frodo
    dns:
      - 10.2.0.2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    networks:
      backend:
        ipv4_address: 10.2.0.10

  ubnt:
    build: ./ubnt
    domainname: netlab
    dns_search: netlab
    hostname: sam
    dns: 10.2.0.2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    networks:
      backend:
        ipv4_address: 10.2.0.15

  redis:
    image: redis:alpine
    domainname: netlab
    dns_search: netlab
    hostname: elrond
    dns: 10.2.0.2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
      - ./redis/:/data
    networks:
      backend:
        ipv4_address: 10.2.0.120

  syslog:
    image: balabit/syslog-ng:latest
    domainname: netlab
    dns_search: netlab
    hostname: gondor
    dns: 10.2.0.2
    volumes:
      - ./resolv.conf:/etc/resolv.conf
    networks:
      backend:
        ipv4_address: 10.2.0.121

  web:
    image: php:apache
    domainname: netlab
    dns_search: netlab
    hostname: pony
    dns: 10.2.0.2
    volumes:
      - ./web:/var/www/html
      - ./resolv.conf:/etc/resolv.conf
    networks:
      backend:
        ipv4_address: 10.2.0.100

  db:
    image: mysql
    restart: always
    domainname: netlab
    dns_search: netlab
    hostname: moria
    dns:
      - 10.2.0.2
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./resolv.conf:/etc/resolv.conf
    environment:
        MYSQL_ROOT_PASSWORD: abc123
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_ONETIME_PASSWORD: "yes"
        MYSQL_INITDB_SKIP_TZINFO: "yes"
        MYSQL_DATABASE: "LOTR"
        MYSQL_USER: "gandalf"
        MYSQL_PASSWORD: "melon"
    networks:
      backend:
        ipv4_address: 10.2.0.101

  dns:
    image: strm/dnsmasq
    domainname: netlab
    dns_search: netlab
    hostname: bree
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    networks:
      backend:
        ipv4_address: 10.2.0.2

networks:
  #frontend:
  #  driver: "bridge"
  #  ipam:
  #    config:
  #      - subnet: "10.1.0.0/16"
  backend:
    driver: "bridge"
    ipam:
      config:
        - subnet: "10.2.0.0/16"
